CREATE DATABASE mads;
USE mads;

CREATE TABLE ROLES (
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION varchar(25) NOT NULL
);
INSERT INTO ROLES (DESCRIPCION)
VALUES ("Propietario");
INSERT INTO ROLES (DESCRIPCION)
VALUES ("Inmobiliaria");


CREATE TABLE USUARIOS (
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
    ROL INT(6),
    USER varchar(25) NOT NULL,
    PASSWORD varchar(25) NOT NULL,
    FOREIGN KEY (ROL) REFERENCES ROLES (id) ON DELETE SET NULL
);

INSERT INTO USUARIOS (ROL, USER, PASSWORD)
VALUES (1,'Juan Perez','DEMO');
INSERT INTO USUARIOS (ROL, USER, PASSWORD)
VALUES (2,'Inmobiliario Trebol','DEMO');
INSERT INTO USUARIOS (ROL, USER, PASSWORD)
VALUES (1,'Rodrigo Juarez','DEMO');
INSERT INTO USUARIOS (ROL, USER, PASSWORD)
VALUES (1,'Nora Cardozo','DEMO');
INSERT INTO USUARIOS (ROL, USER, PASSWORD)
VALUES (2,'Inmobiliario Marquex','DEMO');


CREATE TABLE PROPIEDADES (
	id INT(8) AUTO_INCREMENT PRIMARY KEY,
	UBICACION varchar(50) NOT NULL,
	HABITACIONES int(1) NOT NULL,
	PRECIO float4 NOT NULL,
	PROPIETARIO INT(6),
	FOREIGN KEY (PROPIETARIO) REFERENCES USUARIOS (id) ON DELETE SET NULL	
);

INSERT INTO PROPIEDADES (UBICACION, HABITACIONES, PRECIO, PROPIETARIO)
VALUES ('Zona Nueva Cordoba', 1, 13500.00, 1);
INSERT INTO PROPIEDADES (UBICACION, HABITACIONES, PRECIO, PROPIETARIO)
VALUES ('Nva Cba sobre Estrada', 2, 15500.00, 2);
INSERT INTO PROPIEDADES (UBICACION, HABITACIONES, PRECIO, PROPIETARIO)
VALUES ('Barrio Gral Paz', 2, 21500.00, 3);
INSERT INTO PROPIEDADES (UBICACION, HABITACIONES, PRECIO, PROPIETARIO)
VALUES ('Nva Cba sobre Bolivia', 1, 15500.00, 4);
INSERT INTO PROPIEDADES (UBICACION, HABITACIONES, PRECIO, PROPIETARIO)
VALUES ('Zona Nva Cba sobre Estrada', 1, 19000.00, 5);
INSERT INTO PROPIEDADES (UBICACION, HABITACIONES, PRECIO, PROPIETARIO)
VALUES ('Alta Cordoba', 2, 19000.00, 5);
INSERT INTO PROPIEDADES (UBICACION, HABITACIONES, PRECIO, PROPIETARIO)
VALUES ('Zona Cofico', 2, 18500.00, 5);


CREATE TABLE PUBLICACIONES (
	id INT(8) AUTO_INCREMENT PRIMARY KEY,
    FECHAPUBLICACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USUARIO INT(6),
    PROPIEDAD INT(6),
	FOREIGN KEY (USUARIO) REFERENCES USUARIOS (id) ON DELETE SET NULL,
	FOREIGN KEY (PROPIEDAD) REFERENCES PROPIEDADES (id) ON DELETE SET NULL
);

INSERT INTO PUBLICACIONES (USUARIO, PROPIEDAD) VALUES (1,1);
INSERT INTO PUBLICACIONES (USUARIO, PROPIEDAD) VALUES (2,2);
INSERT INTO PUBLICACIONES (USUARIO, PROPIEDAD) VALUES (3,3);
INSERT INTO PUBLICACIONES (USUARIO, PROPIEDAD) VALUES (4,4);
INSERT INTO PUBLICACIONES (USUARIO, PROPIEDAD) VALUES (5,5);
INSERT INTO PUBLICACIONES (USUARIO, PROPIEDAD) VALUES (5,6);


CREATE PROCEDURE `LISTAR_PUBLICACIONES`()
BEGIN
	SELECT Pub.ID, Pro.UBICACION, Pro.HABITACIONES, Pro.PRECIO, U.USER ,Pub.FECHAPUBLICACION 
	FROM PUBLICACIONES Pub
	INNER JOIN PROPIEDADES Pro ON (Pub.PROPIEDAD = Pro.ID)
	INNER JOIN USUARIOS U ON (Pub.USUARIO = U.ID);
END


